# Generated by Django 3.0.4 on 2020-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlotsLy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_points', models.TextField(help_text='[0, 1, 2]', max_length=1000)),
                ('y_points', models.TextField(help_text='[0, 1, 2]', max_length=1000)),
            ],
        ),
    ]
