# Generated by Django 3.0.4 on 2020-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotsly',
            name='x_points',
            field=models.TextField(default='[0, 1, 2]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plotsly',
            name='y_points',
            field=models.TextField(default='[0, 1, 2]', max_length=1000),
        ),
    ]
