# Generated by Django 3.0.4 on 2020-03-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='plots/default.jpg', upload_to='plots'),
        ),
    ]
